# Generated by Django 3.1.2 on 2020-10-03 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d95a3f6f-c9ca-4895-9fe9-181e9f0edf49'), editable=False, primary_key=True, serialize=False)),
                ('display_name', models.TextField(max_length=32)),
                ('birthday', models.TextField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
