# Generated by Django 3.1.2 on 2020-10-26 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FloofGang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
